### ISSUE TITLE
process of the project

### ISSUE THREAD

**Issue by wahaha-1** [KumarRobotics/CoverageControl#1]
Could you please give me the specific usage process of the project? I still had problems after referring to quick use, and coveragecontrol did not appear after cmake.

**Comment by AgarwalSaurav** [comment]
Can you please provide more details? Send the CMakeLists.txt file and the errors you received when compiling.

Have you successfully installed the package? 
[Installation](https://kumarrobotics.github.io/CoverageControl/installation.html)

**Comment by wahaha-1** [comment]
I'm not quite sure if I installed it correctly, here is a screenshot of my pycharm. The first installation method I used (
pip install coverage_control), and I have installed all the libraries mentioned below.
![9175ab52-5106-4df7-810a-1adc7238cdff](https://github.com/KumarRobotics/CoverageControl/assets/153339362/77d8f39c-6107-405f-8e83-5f887b811d6f)

**Comment by wahaha-1** [comment]
Thank you for your reply. I have successfully run the part of LPAC Neural Network. And for the CoverageControl/CMakeLists.txt path, I got this folder after running.(The system is ubuntu22.04)
![bf78a610-84ea-4a6e-ae8b-b9f1e8fc7b8e](https://github.com/KumarRobotics/CoverageControl/assets/153339362/b16db0b2-09fa-4db0-a268-931d47d5f80a)

**Comment by wahaha-1** [comment]
I tried to understand the overall structure of the file through the description of the file on your website, but I have never been exposed to python+c++ projects before, and I don’t quite understand how to use your project. If possible, I hope you can give me some guidance.

**Comment by wahaha-1** [comment]
very sorry, this is the error message
![44a95179-ac00-48d7-99fe-8cf66146a826](https://github.com/KumarRobotics/CoverageControl/assets/153339362/a6512778-7714-4c1a-8aa1-cacbe5b94944)

**Comment by wahaha-1** [comment]
very sorry, this is the error message
![b782266b-bcd0-40de-8662-8c9b0e350a24](https://github.com/KumarRobotics/CoverageControl/assets/153339362/e75d3575-47f0-4899-a3e7-0a1915a264fd)

**Comment by wahaha-1** [comment]
I used the reference example：


cmake_minimum_required(VERSION 3.16)
project(CoverageControlMain LANGUAGES CXX)

if(NOT CMAKE_BUILD_TYPE)
	set(CMAKE_BUILD_TYPE Release)
endif()

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_COLOR_DIAGNOSTICS ON)

include(CheckCXXCompilerFlag)
include(GNUInstallDirs)

if(NOT DEFINED WITH_TORCH)
	set(WITH_TORCH OFF)
endif()
if(WITH_TORCH)
	find_package(Torch REQUIRED)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
	get_filename_component(TORCH_LIBRARY_DIR "${TORCH_LIBRARIES}" DIRECTORY)
	set(CMAKE_INSTALL_RPATH "${ORIGIN};${CMAKE_INSTALL_LIBDIR};${TORCH_LIBRARY_DIR}")
endif()

find_package(CoverageControl REQUIRED)

if(WITH_TORCH)
	find_package(CoverageControlTorch REQUIRED)
endif()

add_library(compiler_flags INTERFACE)
target_compile_features(compiler_flags INTERFACE cxx_std_17)

set(gcc_like_cxx "$<COMPILE_LANG_AND_ID:CXX,ARMClang,AppleClang,Clang,GNU,LCC>")
set(msvc_cxx "$<COMPILE_LANG_AND_ID:CXX,MSVC>")
target_compile_options(compiler_flags INTERFACE
	"$<${gcc_like_cxx}:$<BUILD_INTERFACE:-Wall;-Wextra;-Wshadow;-Wformat=2;-Wunused;-pedantic>>"
	"$<${msvc_cxx}:$<BUILD_INTERFACE:-W3>>"
)

#################
## Executables ##
#################

add_executable(coverage_algorithm coverage_algorithm.cpp)
target_link_libraries(coverage_algorithm PRIVATE CoverageControl::CoverageControl)
install(TARGETS coverage_algorithm DESTINATION ${CMAKE_INSTALL_BINDIR})

# if(WITH_TORCH)
# 	add_executable(eval_dist_gnn torch/eval_dist_gnn.cpp)
# 	target_link_libraries(eval_dist_gnn PRIVATE compiler_flags CoverageControl CoverageControlTorch ${CUDA_cusparse_LIBRARY})
# 	install(TARGETS eval_dist_gnn DESTINATION ${CMAKE_INSTALL_BINDIR})
# endif()

**Comment by wahaha-1** [comment]
I'm sorry, but I've been trying to learn a little bit about multi-bot area coverage lately, trying to run some projects, but it didn't go well, and I didn't get a reply after asking the author, so I'm probably overly excited when I see your reply, and I hope you ignore my stupid mistakes in running the code

**Comment by AgarwalSaurav** [comment]
You will need to follow "Installation from source," including "Building the core C++ library."
https://kumarrobotics.github.io/CoverageControl/installation.html#installation-from-source

By the way, you can use Python if you are more familiar with it so that you don't have to deal with C++ code. The C++ functions are available in Python.

**Comment by wahaha-1** [comment]
Thank you very much, I will be going to try it soon
